spring.application.name=calculator

#Swagger
springdoc.swagger-ui.enabled=true

server.error.include-message=always
server.error.include-binding-errors=always
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8

# Datasource MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/calculator_db?useSSL=false&serverTimezone=America/Sao_Paulo
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=urubu100

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
